post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphIiwiaWQiOiI1ZGFmYzk0MTYzZjc1YTFlZTA4ZTdhZGUiLCJpYXQiOjE1NzE4MDE1MjF9.NUHucaoP5CDquD4bHuqX123A1Xg5uzvYyrzgDDYqMtE

{
  "title": "Testilähetys",
  "author": "toimi",
  "url": "www.google.com"
}