post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvaW1pIiwiaWQiOiI1ZGFmNTY1NWFkODgyOTRhMWM3NmVhZGUiLCJpYXQiOjE1NzE3OTg4NDB9.-gkefjl5yXP_Nxa3uPMGHlid0nYtMldELyg8RVIx23A

{
  "title": "Testilähetys",
  "author": "toimi",
  "url": "www.google.com"
}